
MANUFACTURER2COUNTRY = {
    'Alfa Romeo': 'Italy',
    'Aston Martin': 'UK',
    'Audi': 'Germany',
    'BMW': 'Germany',
    'Chevrolet': 'USA',
    'Chrysler': 'USA',
    'Citroën': 'France',
    'Daihatsu': 'Japan',
    'Dodge': 'USA',
    'Fiat': 'Italy',
    'Ford': 'USA',
    'Honda': 'Japan',
    'Jaguar': 'UK',
    'Lancia': 'Italy',
    'Lister': 'UK',
    'Lotus': 'UK',
    'MG': 'UK',
    'Mazda': 'Japan',
    'Mercedes-Benz': 'Germany',
    'Mercury': 'USA',
    "Mine's": 'Japan',
    'Mini': 'UK',
    'Mitsubishi': 'Japan',
    'Mugen': 'Japan',
    'Nismo': 'Japan',
    'Nissan': 'Japan',
    'Opel': 'Germany',
    'Peugeot': 'France',
    'Plymouth': 'USA',
    'RE Amemiya': 'Japan',
    'RUF': 'Germany',
    'Renault': 'France',
    'Saleen': 'USA',
    'Shelby': 'USA',
    'Spoon': 'Japan',
    'Subaru': 'Japan',
    'Suzuki': 'Japan',
    'TRD': 'Japan',  # Toyota Racing Development
    'TVR': 'UK',
    "Tom's": 'Japan',
    'Tommy Kaira': 'Japan',
    'Toyota': 'Japan',
    'Vector': 'USA',
    'Venturi': 'France',
    'Volkswagen': 'Germany',
}

COUNTRY2CONTINENT = {
    'France': 'Europe',
    'Germany': 'Europe',
    'Italy': 'Europe',
    'Japan': 'Asia',
    'USA': 'America',
    'UK': 'Europe',
}

IGNNAME2WIKINAME = {
    "bp trueno gt '99": "Toyota BP APEX KRAFT Trueno GT (JGTC) '99",
    'mx-5 miata c spec': "Mazda MX-5 C-Spec",
    'momocorse mr2': "Toyota Momo Corse Apex MR2 GT (JGTC) '99",
    "mugen nsx gt '99": "Honda Castrol Mugen NSX GT (JGTC) '99",
    "r390 gt1 lm race car '97": "Nissan R390 GT1 Race Car '97",
    "r390 gt1lm race car'98": "Nissan R390 GT1 Race Car '98",
    'spoon civic type-r': "Spoon CIVIC TYPE R (EK) '00",
    'trd3000gt': "TRD 3000GT",
    'chaser trd sports x3': "TRD Chaser Sports X30",
    "cobra 427 '67": "Shelby Cobra 427 '66",
    "denso supra gt '99": "Toyota Denso Sard Supra GT (JGTC) '99",
    "gt-one race car '98": "Toyota GT-ONE Race Car (TS020) '98",
    'impreza wagon sti ver. v': "Subaru IMPREZA Sport Wagon WRX STi Version V '98",
    'kure r33 gt': "Nissan Kure R33 Skyline GT (JGTC) '97",
    'legacy wagon gt-b': "Subaru LEGACY Touring Wagon GT-B '96",
    'mx-5 miata a spec': "Mazda MX-5 A-Spec",
    'mugen cr-x ii': "Mugen CR-X Pro.2",
    'mugen cr-x iii': "Mugen CR-X Pro.3",
    'mugen civic type-r': "Mugen Civic Type R",
    'mugen ferio': "Mugen Civic Ferio",
    'mugen integra type-$': "Mugen Integra Type R",
    'nissan 300zx gt': "Nissan 300ZX-GTS GT (JGTC) '97",
    'plymouth spyder': "Plymouth PT Spyder",
    'spoon integra type-r': "Spoon INTEGRA TYPE R (DC2) '99",
    "supra gt '99": ["Toyota cdma One CERUMO Supra GT (JGTC) '99", "Toyota Denso Sard Supra GT (JGTC) '99 "],
    'trd2000gt': "TRD 2000GT",
    "tom's t020": "Tom’s (Toyota) T020",
    "tom's t111": "Tom’s (Toyota) T111",
    'unisia gt-r gt': "Nissan Unisia Jecs Skyline GT (JGTC) '99",
    'zz iii': "Tommy Kaira ZZ-III",
    'zzii': "Tommy Kaira ZZ-II '99",
}


DRIVETRAIN_MAPPING = {
    '(GT1, GT2 PAL version) FR(GT2 NTSC versions) MR': 'FR',
    '(GT1, GT2 PAL version) FR (GT2 NTSC/NTSC-J versions) MR': 'FR',
    'FF (unlisted in GT4)': 'FF',
    '4WD (GT2)FR (GT3-6)': '4WD',
}


COLUMNS_TO_DISCARD = [
    'Aspiration',
    'Type in GT5',
    'Interior in GT6',
    'Performance Points',
    'Top Speed',
    '0-60 Mph',
    'Standing Quarter Mile',
    'Internal ID',
 ]
